name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'

permissions:
  contents: read

env:
  AWS_REGION: us-east-2
  ECR_REGISTRY: 128955061512.dkr.ecr.us-east-2.amazonaws.com
  ECR_REPOSITORY: hello-world

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure AWS creds from GitHub secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR (runtime password)
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin $ECR_REGISTRY
      
      - name: Set image variables
        run: |
          echo "IMAGE_URI=${ECR_REGISTRY}/${ECR_REPOSITORY}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_EN

      - name: Build and push
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t "${IMAGE_URI}:${IMAGE_TAG}" \
            -f Dockerfile \
            . \
            --push

